### ISSUE TITLE
which Ghibli lora?

### ISSUE THREAD

**Issue by vesper8** [sepro/SDXL-ComfyUI-workflows#1]
Hey! First of all thanks a lot for sharing your workflows and explanations.. this is helping me learn a lot!

Your photography workflow makes use of a Lora named 'ghibli_last.safetensors', but I'm struggling to find out which one it is.. there aren't any Loras on the usual sites named that way. Are you referring to https://civitai.com/models/6526/studio-ghibli-style-lora ? This seems to be the most popular Ghibli lora right now.

If not could you specify where I can download the one you used?

Thanks!

**Comment by sepro** [comment]
Hi. Glad you enjoy the workflows.

Actually the weight of that node is set to zero, it is there in case someone wants to use an additional lora without rewiring to any nodes. However, it seems to have stored the first lora (alphabetically) I've got in my folder in the workflow. 

The one I've got can be is this one: https://civitai.com/models/120860/sdxl10-ghibli-style-v1 . If you are after that style, I'd recommend using painterly_style_workflow.json in combination with this LoRa.
