### ISSUE TITLE
Links broken and Workflow files doesnt work

### ISSUE THREAD

**Issue by supersailor** [sepro/SDXL-ComfyUI-workflows#2]
Hi!

Looks sweet but the links on page doesnt work. Workflows work only if you open them and download the raw file.

**Comment by sepro** [comment]
Fixed the links, thanks for bringing this to my attention. 

To get files through GitHub's web interface indeed the raw files need to be downloaded. They are also available from [https://blog.4dcu.be/aiart/2023/09/03/comfyui-sdxl-workflows.html](https://blog.4dcu.be/aiart/2023/09/03/comfyui-sdxl-workflows.html) as a regular download.
